### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by sahithi-kukkala** [yufanchen96/RoDLA#3]

**Comment by sahithi-kukkala** [comment]
hello,
i installed the packages according to the instructions in the github page  
# create virtual environment
conda create -n RoDLA python=3.7 -y
conda activate RoDLA

pip install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html
pip install -U openmim
mim install mmcv-full==1.5.0
pip install timm==0.6.11 mmdet==2.28.1
pip install Pillow==9.5.0
pip install opencv-python termcolor yacs pyyaml scipy

but pyiqa is not compatible with above packages as it needs torch >= 1.12 and torchvision >=1.13

i am not able to run the model , how should i proceed?

**Comment by yufanchen96** [comment]
You could try 
pip install pyiqa==0.1.7
